# Generated by Django 5.0.6 on 2024-07-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wiki',
            new_name='Wikis',
        ),
    ]
